# Generated by Django 4.2.7 on 2023-12-18 12:21

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=15, unique=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
    ]
